name: py lint
on:
  pull_request:
    branches:
      - main
jobs:
  line-lint:
    name: line lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install requirements
        run: pip3 install -r requirements.txt
      - name: install pylint
        run: pip3 install pylint
      - name: pylint
        run: pylint --rcfile=.pylintrc .
